Document: glassplayer
Title: Debian glassplayer Manual
Author: <insert document author here>
Abstract: This manual describes what glassplayer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/glassplayer/glassplayer.sgml.gz

Format: postscript
Files: /usr/share/doc/glassplayer/glassplayer.ps.gz

Format: text
Files: /usr/share/doc/glassplayer/glassplayer.text.gz

Format: HTML
Index: /usr/share/doc/glassplayer/html/index.html
Files: /usr/share/doc/glassplayer/html/*.html
